import { and, asc, eq, gte, lte } from 'drizzle-orm';
import type { Db } from '../db/client.js';
import { orgs, sopDocuments, trainingEvents, workers } from '../db/schema.js';
import { formatDateTimeEn } from '../lib/time.js';
import { maskPhone } from '../lib/phone.js';
import { PDF_COLORS, pdfToBuffer } from './pdf.js';

const EVENT_LABELS: Record<string, string> = {
  qa_interaction: 'Q&A interaction',
  module_delivered: 'Training module delivered',
  check_passed: 'Comprehension check — PASSED',
  check_failed: 'Comprehension check — missed',
  escalation: 'Escalated to supervisor',
};

/**
 * Per-worker training transcript: every training_event in chronological
 * order. Used by the worker detail page download and inside audit packs.
 */
export async function generateWorkerTranscriptPdf(
  db: Db,
  workerId: string,
  period?: { start: Date; end: Date },
): Promise<Buffer> {
  const [worker] = await db.select().from(workers).where(eq(workers.id, workerId));
  if (!worker) throw new Error('Worker not found');
  const [org] = await db.select().from(orgs).where(eq(orgs.id, worker.orgId));

  const conditions = [eq(trainingEvents.workerId, workerId), eq(trainingEvents.orgId, worker.orgId)];
  if (period) {
    conditions.push(gte(trainingEvents.occurredAt, period.start));
    conditions.push(lte(trainingEvents.occurredAt, period.end));
  }
  const events = await db
    .select({ ev: trainingEvents, docTitle: sopDocuments.title })
    .from(trainingEvents)
    .leftJoin(sopDocuments, eq(trainingEvents.sourceDocumentId, sopDocuments.id))
    .where(and(...conditions))
    .orderBy(asc(trainingEvents.occurredAt));

  const tz = org.timezone;

  return pdfToBuffer({ size: 'LETTER', margins: { top: 54, bottom: 54, left: 54, right: 54 } }, (doc) => {
    doc.font('Helvetica-Bold').fontSize(11).fillColor(PDF_COLORS.accent);
    doc.text('ESTABLO', { characterSpacing: 3 });
    doc.font('Helvetica').fontSize(8).fillColor(PDF_COLORS.muted);
    doc.text('Verified WhatsApp training records');
    doc.moveDown(0.8);

    doc.font('Helvetica-Bold').fontSize(16).fillColor(PDF_COLORS.ink);
    doc.text('Training Transcript');
    doc.moveDown(0.3);
    doc.font('Helvetica').fontSize(10).fillColor(PDF_COLORS.ink);
    doc.text(`Employee: ${worker.name}`);
    doc.text(`Phone: ${maskPhone(worker.phoneE164)}`);
    doc.text(`Operation: ${org.name}`);
    if (period) {
      doc.text(
        `Period: ${formatDateTimeEn(period.start, tz)} — ${formatDateTimeEn(period.end, tz)}`,
      );
    }
    doc.text(`Training events in this transcript: ${events.length}`);
    doc.moveDown(0.5);
    doc
      .moveTo(doc.page.margins.left, doc.y)
      .lineTo(doc.page.width - doc.page.margins.right, doc.y)
      .stroke(PDF_COLORS.line);
    doc.moveDown(0.5);

    if (events.length === 0) {
      doc.font('Helvetica-Oblique').fontSize(10).fillColor(PDF_COLORS.muted);
      doc.text('No training events recorded in this period.');
    }

    for (const { ev, docTitle } of events) {
      if (doc.y > doc.page.height - 130) doc.addPage();
      doc.font('Helvetica-Bold').fontSize(9.5).fillColor(PDF_COLORS.accent);
      doc.text(
        `${formatDateTimeEn(ev.occurredAt, tz)}  ·  ${EVENT_LABELS[ev.eventType] ?? ev.eventType}  ·  ${ev.topic}`,
      );
      doc.font('Helvetica').fontSize(9).fillColor(PDF_COLORS.ink);
      if (ev.questionText) {
        doc.text(`Q: ${ev.questionText}`, { indent: 10 });
      }
      if (ev.answerText) {
        const answer =
          ev.answerText.length > 600 ? `${ev.answerText.slice(0, 600)}…` : ev.answerText;
        doc.text(`A: ${answer.replace(/📄/gu, '')}`, { indent: 10 });
      }
      // Only the source title — confidence is an internal retrieval-quality
      // signal, not something an exported document should carry.
      if (docTitle) {
        doc.font('Helvetica-Oblique').fontSize(8).fillColor(PDF_COLORS.muted);
        doc.text(`Source: ${docTitle}`, { indent: 10 });
      }
      doc.moveDown(0.55);
    }

    doc.moveDown(1);
    doc.font('Helvetica-Oblique').fontSize(8).fillColor(PDF_COLORS.muted);
    doc.text(
      `Generated by Establo on ${formatDateTimeEn(new Date(), tz)}. Each entry corresponds to a logged training_event record.`,
    );
  });
}
